title: Ram N
description: Data science, Education, Tinkering 
# theme: jekyll-theme-minimal

plugins:
  - jekyll-seo-tag

collections:
  projects:
    output: true

# Optional (appears in sidebar)
logo: https://avatars.githubusercontent.com/Ram-N?size=150
show_downloads: false


# Social links
github:
  username: Ram-N
linkedin: https://www.linkedin.com/in/ramnarasimhan1/
goodreads: https://www.goodreads.com/user/show/37469588-ramnarasimhan
