title: Ram N
description: Data scientist, educator, generative art explorer
theme: jekyll-theme-minimal

# Optional (appears in sidebar)
logo: https://avatars.githubusercontent.com/Ram_N?size=150
show_downloads: false

# Social links
github:
  username: Ram-N
linkedin: yourprofile
goodreads: https://www.goodreads.com/user/show/37469588-ramnarasimhan
